/* eslint-disable */
const fs = require('fs');
const path = require('path');

const RED = '\x1b[31m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RESET = '\x1b[0m';

console.log(`${YELLOW}🔧 Setting up Git Hooks...${RESET}`);

const gitDir = path.resolve(__dirname, '../.git');
const hooksDir = path.resolve(gitDir, 'hooks');
const preCommitHookPath = path.resolve(hooksDir, 'pre-commit');

if (!fs.existsSync(gitDir)) {
  console.log(`${RED}⚠️ .git directory not found. Skipping hook installation. (Make sure this is a Git repository)${RESET}`);
  process.exit(0);
}

if (!fs.existsSync(hooksDir)) {
  fs.mkdirSync(hooksDir, { recursive: true });
}

// Use regular string (NOT template literal) to prevent JS variable interpolation into shell script
const hookContent = '#!/bin/sh\n'
  + '# Auto-generated by setup-hooks.js - DO NOT EDIT MANUALLY\n'
  + '\n'
  + 'echo "\\033[33m🔄 Running local pre-commit checks...\\033[0m"\n'
  + 'node scripts/security-validator.js\n'
  + '\n'
  + '# Capture the exit code of the validator\n'
  + 'EXIT_CODE=$?\n'
  + '\n'
  + 'if [ $EXIT_CODE -ne 0 ]; then\n'
  + '  echo "\\033[31m🛑 Commit aborted due to security warnings. Check the errors above.\\033[0m"\n'
  + '  exit 1\n'
  + 'fi\n'
  + '\n'
  + 'exit 0\n';

try {
  fs.writeFileSync(preCommitHookPath, hookContent, { encoding: 'utf8', mode: 0o755 });
  
  // Explicitly try to set permissions again to be safe on UNIX-like environments
  try {
    fs.chmodSync(preCommitHookPath, '755');
  } catch (e) {
    // Ignore permissions errors (e.g., on Windows filesystems where chmod behaves differently)
  }

  console.log(`${GREEN}✅ Git Hook 'pre-commit' installed successfully!${RESET}`);
} catch (error) {
  console.error(`${RED}❌ Failed to install Git hooks: ${error.message}${RESET}`);
}
