/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const MASTER_FILE = path.join(ROOT_DIR, '.cursorrules');

const TARGET_FILES = [
  '.clinerules',
  '.agentrules',
  '.windsurfrules',
  'claude.md'
];

const WARNING_HEADER = `[//]: # (⚠️ WARNING: DO NOT EDIT THIS FILE! ⚠️)
[//]: # (This file is AUTO-GENERATED by scripts/sync-rules.js)
[//]: # (Please edit .cursorrules instead. Any changes here will be OVERWRITTEN.)

`;

console.log('🔄 Memulai Sinkronisasi AI Rules (Strict Master)...');

try {
  if (!fs.existsSync(MASTER_FILE)) {
    throw new Error('Master file .cursorrules tidak ditemukan!');
  }

  // 1. Baca Master Prompt
  const masterContent = fs.readFileSync(MASTER_FILE, 'utf-8');
  console.log(`✅ Berhasil membaca master prompt: .cursorrules`);

  // 2. Gabungkan Header dan Konten
  const finalContent = WARNING_HEADER + masterContent;

  // 3. Salin ke file target
  for (const file of TARGET_FILES) {
    const targetPath = path.join(ROOT_DIR, file);
    fs.writeFileSync(targetPath, finalContent, 'utf-8');
    console.log(`✅ Tersinkronisasi: ${file}`);
  }

  console.log('🚀 Sinkronisasi selesai! Semua IDE rules terupdate dengan aman.');
} catch (error) {
  console.error('❌ Gagal melakukan sinkronisasi:', error.message);
  process.exit(1);
}
